import { expect, test } from '@playwright/test'
import {
  centerTrigger,
  dropdownDemo,
  expectPlacement,
  gotoDropdown,
  menuFor,
  output,
  rect,
  triggerButton,
  triggerRoot,
  waitMenuClosed,
  waitMenuOpen,
} from '../../utils/dropdown-browser'

// 默认 hover 不抢焦点；跨越触发器与 Portal 的间隙后保持打开，离开或选择后关闭。
test('[dropdown.browser.hover-bridge] 悬停桥接、离开与选择关闭', async ({ page }, info) => {
  await page.clock.install()
  const demo = await gotoDropdown(page, info, 'basic')
  const button = triggerButton(demo, '悬停菜单')
  const root = triggerRoot(button)
  await expect(root).toHaveAttribute('aria-expanded', 'false')
  await expect(root).not.toHaveAttribute('aria-controls')
  await centerTrigger(button)
  await button.focus()
  await button.hover()
  const menu = await menuFor(page, root)
  await waitMenuOpen(menu)
  await expect(button).toBeFocused()

  await menu.getByRole('menuitem', { name: '编辑', exact: true }).hover()
  // 推进 hover 关闭防抖，而不是用固定等待猜测指针是否成功进入浮层。
  await page.clock.runFor(200)
  await waitMenuOpen(menu)
  await expect(root).toHaveAttribute('aria-expanded', 'true')
  await expect(menu.getByRole('separator')).toHaveCount(1)

  await page.mouse.move(1, 1)
  await expect(root).toHaveAttribute('aria-expanded', 'false')
  await waitMenuClosed(menu)
  await button.hover()
  await waitMenuOpen(menu)
  await menu.getByRole('menuitem', { name: '编辑', exact: true }).click()
  await expect(output(demo, '最近操作：')).toHaveText('最近操作：edit')
  await expect(root).toHaveAttribute('aria-expanded', 'false')
  await waitMenuClosed(menu)
})

// 验证原生 Enter/Space 打开、上下键跳过禁用项/分隔线、回调顺序及 Escape 后的真实焦点。
test('[dropdown.browser.keyboard-focus] 键盘导航、激活与焦点归还', async ({ page }, info) => {
  const demo = await gotoDropdown(page, info, 'click')
  const button = triggerButton(demo, '点击菜单')
  const root = triggerRoot(button)
  await centerTrigger(button)
  await button.press('Enter')
  const menu = await menuFor(page, root)
  const first = menu.getByRole('menuitem', { name: '第一项', exact: true })
  const last = menu.getByRole('menuitem', { name: '最后项', exact: true })
  await waitMenuOpen(menu)
  await expect(first).toBeFocused()
  await page.keyboard.press('ArrowDown')
  await expect(last).toBeFocused()
  await page.keyboard.press('Enter')
  await expect(output(demo, '最近操作：')).toHaveText('最近操作：last')
  await expect(demo.locator('[data-dropdown-callbacks]')).toHaveText('回调顺序：item:last → menu:last → close:false')
  await waitMenuClosed(menu)
  await expect(button).toBeFocused()

  await button.press('Space')
  await waitMenuOpen(menu)
  await expect(first).toBeFocused()
  await page.keyboard.press('ArrowUp')
  await expect(last).toBeFocused()
  await page.keyboard.press('ArrowDown')
  await expect(first).toBeFocused()
  await page.keyboard.press('Space')
  await expect(output(demo, '最近操作：')).toHaveText('最近操作：first')
  await expect(demo.locator('[data-dropdown-callbacks]')).toHaveText('回调顺序：item:first → menu:first → close:false')
  await waitMenuClosed(menu)
  await expect(button).toBeFocused()

  await button.press('ArrowUp')
  await waitMenuOpen(menu)
  await expect(last).toBeFocused()
  await page.keyboard.press('Escape')
  await waitMenuClosed(menu)
  await expect(button).toBeFocused()

  // 两个启用项时正反 Tab 的结果相同；用 basic 的三个启用项真正区分 Shift+Tab 方向。
  const hoverButton = triggerButton(dropdownDemo(page, info, 'basic'), '悬停菜单')
  await centerTrigger(hoverButton)
  await hoverButton.press('ArrowDown')
  const hoverMenu = await menuFor(page, triggerRoot(hoverButton))
  await waitMenuOpen(hoverMenu)
  await expect(hoverMenu.getByRole('menuitem', { name: '编辑', exact: true })).toBeFocused()
  await page.keyboard.press('Tab')
  await expect(hoverMenu.getByRole('menuitem', { name: '复制', exact: true })).toBeFocused()
  await page.keyboard.press('Shift+Tab')
  await expect(hoverMenu.getByRole('menuitem', { name: '编辑', exact: true })).toBeFocused()
  await page.keyboard.press('Shift+Tab')
  await expect(hoverMenu.getByRole('menuitem', { name: '删除', exact: true })).toBeFocused()
  await page.keyboard.press('Escape')
  await waitMenuClosed(hoverMenu)
  await expect(hoverButton).toBeFocused()
})

// 两个不同右键位置仍按按钮的边缘定位，防止误实现成鼠标坐标菜单。
test('[dropdown.browser.context-menu] 右键锚定触发器而非光标', async ({ page }, info) => {
  const demo = await gotoDropdown(page, info, 'context-menu')
  const button = triggerButton(demo, '右键菜单')
  const root = triggerRoot(button)
  await centerTrigger(button)
  await button.click({ button: 'right', position: { x: 5, y: 5 } })
  const menu = await menuFor(page, root)
  await waitMenuOpen(menu)
  await expect(menu.getByRole('menuitem', { name: '刷新', exact: true })).toBeFocused()
  await expectPlacement(root, menu, 'bottomLeft')
  await menu.getByRole('menuitem', { name: '刷新', exact: true }).click()
  await expect(output(demo, '最近操作：')).toHaveText('最近操作：refresh')
  await waitMenuClosed(menu)

  const box = await rect(button)
  await button.click({ button: 'right', position: { x: box.width - 5, y: box.height - 5 } })
  await waitMenuOpen(menu)
  await expectPlacement(root, menu, 'bottomLeft')
  await menu.getByRole('menuitem', { name: '置顶', exact: true }).click()
  await expect(output(demo, '最近操作：')).toHaveText('最近操作：pin')
  await expect(root).toHaveAttribute('aria-expanded', 'false')
})

// 外部键盘操作直接更新 open，不产生 pointerdown 关闭请求；用户选择与外部点击的回调另行计数。
test('[dropdown.browser.controlled] 外部开关、回调与受控禁用', async ({ page }, info) => {
  const demo = await gotoDropdown(page, info, 'controlled')
  const button = triggerButton(demo, '受控菜单')
  const root = triggerRoot(button)
  const openButton = triggerButton(demo, '外部打开')
  const closeButton = triggerButton(demo, '外部关闭')
  const openOutput = output(demo, 'open：')
  const callbackOutput = output(demo, '回调次数：')
  await expect(openOutput).toHaveText('open：false')
  await expect(callbackOutput).toHaveText('回调次数：0')
  await centerTrigger(button)
  await openButton.press('Enter')
  const menu = await menuFor(page, root)
  await waitMenuOpen(menu)
  await expect(openOutput).toHaveText('open：true')
  await expect(callbackOutput).toHaveText('回调次数：0')
  await closeButton.press('Enter')
  await waitMenuClosed(menu)
  await expect(openOutput).toHaveText('open：false')
  await expect(callbackOutput).toHaveText('回调次数：0')

  await openButton.press('Enter')
  await waitMenuOpen(menu)
  await expect(menu.getByRole('menuitem', { name: '保存', exact: true })).toBeFocused()
  await page.keyboard.press('Enter')
  await waitMenuClosed(menu)
  await expect(output(demo, '最近操作：')).toHaveText('最近操作：save')
  await expect(callbackOutput).toHaveText('回调次数：1')
  await openButton.press('Enter')
  await waitMenuOpen(menu)
  await closeButton.click()
  await waitMenuClosed(menu)
  await expect(callbackOutput).toHaveText('回调次数：2')

  await triggerButton(demo, '切换受控禁用').click()
  await expect(output(demo, 'disabled：')).toHaveText('disabled：true')
  await openButton.press('Enter')
  await waitMenuOpen(menu)
  // aria-disabled 会阻止 Playwright 的自动点击；强制发送真实指针事件验证组件拦截。
  await button.click({ force: true })
  await expect(openOutput).toHaveText('open：true')
  await expect(callbackOutput).toHaveText('回调次数：2')
  await closeButton.press('Enter')
  await waitMenuClosed(menu)
  await expect(openOutput).toHaveText('open：false')
  await expect(callbackOutput).toHaveText('回调次数：2')
})

// Dropdown.disabled 不依赖子按钮原生 disabled；真实指针点击及键盘导航都跳过禁用/危险禁用项。
test('[dropdown.browser.disabled] 触发器与菜单项禁用', async ({ page }, info) => {
  const demo = await gotoDropdown(page, info, 'disabled')
  const button = triggerButton(demo, '禁用触发器')
  const root = triggerRoot(button)
  await expect(button).toHaveJSProperty('disabled', false)
  await expect(root).toHaveAttribute('aria-disabled', 'true')
  await button.click({ force: true })
  await button.press('ArrowDown')
  await button.press('Space')
  await expect(root).toHaveAttribute('aria-expanded', 'false')
  await expect(root).not.toHaveAttribute('aria-controls')
  await expect(output(demo, '最近操作：')).toHaveText('最近操作：未操作')

  await triggerButton(demo, '切换禁用').click()
  await expect(output(demo, '触发器禁用：')).toHaveText('触发器禁用：false')
  await button.click()
  const enabledMenu = await menuFor(page, root)
  await waitMenuOpen(enabledMenu)
  await enabledMenu.getByRole('menuitem', { name: '恢复后可选', exact: true }).click()
  await expect(output(demo, '最近操作：')).toHaveText('最近操作：enabled')

  const itemsButton = triggerButton(demo, '禁用选项')
  const itemsRoot = triggerRoot(itemsButton)
  await centerTrigger(itemsButton)
  await itemsButton.click()
  const menu = await menuFor(page, itemsRoot)
  await waitMenuOpen(menu)
  const normal = menu.getByRole('menuitem', { name: '普通项', exact: true })
  const danger = menu.getByRole('menuitem', { name: '危险项', exact: true })
  await expect(normal).toBeFocused()
  for (const name of ['禁用项', '禁用危险项']) {
    const item = menu.getByRole('menuitem', { name, exact: true })
    await expect(item).toHaveAttribute('aria-disabled', 'true')
    await expect(item).toHaveCSS('opacity', '0.4')
    await expect(item).toHaveCSS('pointer-events', 'none')
    const box = await rect(item)
    await page.mouse.click(box.left + box.width / 2, box.top + box.height / 2)
    await expect(itemsRoot).toHaveAttribute('aria-expanded', 'true')
    await expect(output(demo, '最近操作：')).toHaveText('最近操作：enabled')
  }
  await normal.focus()
  await page.keyboard.press('ArrowDown')
  await expect(danger).toBeFocused()
  const normalColor = await normal.evaluate(element => getComputedStyle(element).color)
  await expect(danger).not.toHaveCSS('color', normalColor)
  await page.keyboard.press('Enter')
  await expect(output(demo, '最近操作：')).toHaveText('最近操作：danger')
  await waitMenuClosed(menu)
})

// 替换后的键盘焦点只落在新项；空列表/全禁用列表允许 Tab 离开且不产生选择回调。
test('[dropdown.browser.dynamic-items] 动态替换与无可用项菜单', async ({ page }, info) => {
  const demo = await gotoDropdown(page, info, 'dynamic')
  const button = triggerButton(demo, '动态菜单')
  const root = triggerRoot(button)
  await centerTrigger(button)
  await button.click()
  const menu = await menuFor(page, root)
  await waitMenuOpen(menu)
  await expect(menu.getByRole('menuitem', { name: 'A', exact: true })).toBeFocused()
  await triggerButton(demo, '替换选项').click()
  await expect(output(demo, '当前选项：')).toHaveText('当前选项：C / D')
  await waitMenuClosed(menu)
  await button.press('Enter')
  await waitMenuOpen(menu)
  await expect(menu.getByRole('menuitem', { name: 'C', exact: true })).toBeFocused()
  await expect(menu.getByRole('menuitem')).toHaveText(['C', 'D'])
  await page.keyboard.press('ArrowDown')
  await expect(menu.getByRole('menuitem', { name: 'D', exact: true })).toBeFocused()
  await page.keyboard.press('Space')
  await waitMenuClosed(menu)
  await expect(output(demo, '最近操作：')).toHaveText('最近操作：d')

  for (const name of ['空菜单', '全禁用菜单']) {
    const emptyButton = triggerButton(demo, name)
    await emptyButton.press('Enter')
    const emptyMenu = await menuFor(page, triggerRoot(emptyButton))
    await waitMenuOpen(emptyMenu)
    await expect(emptyMenu).toBeFocused()
    await expect(emptyMenu.getByRole('menuitem')).toHaveCount(name === '空菜单' ? 0 : 2)
    for (const item of await emptyMenu.getByRole('menuitem').all()) {
      await expect(item).toHaveAttribute('aria-disabled', 'true')
    }
    await page.keyboard.press(name === '空菜单' ? 'Tab' : 'Shift+Tab')
    await waitMenuClosed(emptyMenu)
    await expect(emptyMenu).not.toBeFocused()
    await expect(output(demo, '最近操作：')).toHaveText('最近操作：d')
  }
})

// 使用可控时钟验证默认打开、关闭 DOM 留存/复用/销毁，160ms 旧聚焦任务不得在快速关闭或卸载后抢焦点。
test('[dropdown.browser.lifecycle-focus-race] 生命周期与快速关闭焦点竞态', async ({ page }, info) => {
  await page.clock.install()
  const demo = await gotoDropdown(page, info, 'lifecycle')
  const mount = triggerButton(demo, '挂载默认打开')
  const unmount = triggerButton(demo, '卸载菜单')
  const button = triggerButton(demo, '默认打开菜单')
  await expect(button).toHaveCount(0)
  await expect(page.getByRole('menuitem', { name: '默认打开菜单项', exact: true, includeHidden: true })).toHaveCount(0)
  await centerTrigger(mount)
  await page.clock.pauseAt(await page.evaluate(() => Date.now()) + 1000)
  await mount.click()
  const root = triggerRoot(button)
  const menu = await menuFor(page, root)
  await page.clock.runFor(200)
  await waitMenuOpen(menu)
  await expect(menu.getByRole('menuitem', { name: '默认打开菜单项', exact: true })).toBeFocused()
  await expect(output(demo, '最近开关请求：')).toHaveText('最近开关请求：未触发')
  const original = await menu.elementHandle()
  if (!original) throw new Error('defaultOpen did not mount its menu')
  const originalId = await menu.getAttribute('id')

  await page.keyboard.press('Escape')
  await waitMenuClosed(menu)
  await expect(menu).toHaveCount(1)
  await expect(menu).toHaveJSProperty('inert', true)
  await button.press('Enter')
  await page.clock.runFor(200)
  await waitMenuOpen(menu)
  expect(await original.evaluate(element => element.isConnected)).toBe(true)
  await expect(root).toHaveAttribute('aria-controls', originalId!)
  await page.keyboard.press('Escape')
  await page.clock.runFor(1400)
  await expect(menu).toHaveCount(0)
  await expect(root).not.toHaveAttribute('aria-controls')
  expect(await original.evaluate(element => element.isConnected)).toBe(false)
  await original.dispose()

  await button.press('Enter')
  await page.clock.runFor(32)
  await expect(root).toHaveAttribute('aria-expanded', 'true')
  await page.keyboard.press('Escape')
  await mount.focus()
  await page.clock.runFor(200)
  await waitMenuClosed(menu)
  await expect(mount).toBeFocused()
  await expect(root).toHaveAttribute('aria-expanded', 'false')

  await button.press('Enter')
  await page.clock.runFor(32)
  await unmount.click()
  await page.clock.runFor(1400)
  await expect(menu).toHaveCount(0)
  await expect(button).toHaveCount(0)
  await expect(unmount).toBeFocused()
  await expect(output(demo, '挂载状态：')).toHaveText('挂载状态：未挂载')
  await mount.click()
  const remounted = await menuFor(page, triggerRoot(button))
  await page.clock.runFor(200)
  await waitMenuOpen(remounted)
  await expect(remounted).not.toHaveAttribute('id', originalId!)
  await unmount.click()
  await expect(remounted).toHaveCount(0)
})
