packages:
  - 'packages/*'
  - 'example'

overrides:
  "@solid-primitives/refs": "1.1.3"
  "@solid-primitives/props": "3.2.3"

onlyBuiltDependencies:
  - esbuild

allowBuilds:
  esbuild: true
  '@parcel/watcher': true
  msw: true
